networks:
  dev:

services:
  # envoy:
  #   image: envoyproxy/envoy:dev-b10deb602383972cd71ab0a836c846f7eb91b790
  #   ports: 
  #     - "8080:8080"
  #   volumes:
  #     - ./proxy/envoy/envoy.yaml:/etc/envoy/envoy.yaml

  envoy:
    build: 
      ./proxy/envoy
    ports:
      - "8080:8080"
    networks:
      - dev
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "9090:9090"
    networks:
      - dev

  # frontend:
  #   build:
  #     context: ./frontend

  # bot:
  #   build:
  #     context: ./bot
