networks:
  dev:

services:

  envoy:
    build: 
      ./proxy/envoy
    ports:
      - "8080:8080"
    networks:
      - dev
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    volumes:
      - ../shared:/backend/shared
    ports:
      - "9090:9090"
    networks:
      - dev