networks:
  dev:


services:
  envoy:
    build: ./proxy/envoy
    ports:
      - "8080:8080"
    networks:
      - dev
    depends_on:
      - backend

  # nginx:
  #   build: ./proxy/nginx
  #   networks:
  #     - dev
  #   depends_on:
  #     - envoy
  #     - backend
  #     - frontend

  backend:
    build:
      context: ./backend
    ports:
      - "9090:9090"
    networks:
      - dev
    volumes:
      - './backend/db.sqlite:/backend/db.sqlite'
    develop:
      watch:
        - action: rebuild
          path: ./backend/lib/


  # frontend:
  #   build:
  #     context: ./frontend
  #   networks:
  #     - dev
  #   depends_on:
  #     - nginx

  # bot:
  #   build: ./bot
  # networks:
  #   - dev
  # depends_on:
  #   - nginx
