networks:
  dev:


services:

  envoy:
    build: ./proxy/envoy
    ports:
      - "8080:8080"
    networks:
      - dev
    depends_on:
      - backend

  nginx:
    build: ./proxy/nginx
    networks:
      - dev
    depends_on:
      - envoy
      - backend
      - frontend

  backend:
    build:
      context: ./backend
    volumes:
      - ../shared:/backend/shared
    ports:
      - "9090:9090"
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
    depends_on:
      - nginx
