name: common
publish_to: 'none'

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  drift: ^2.23.1
  sqlite3: ^2.4.6
  grpc: ^4.0.4
  protobuf: ^4.0.0
  l: ^4.0.2
  crypto: ^3.0.5
  schedules: ^0.0.5
  http: ^1.2.2
  html: ^0.15.4
  shared:
    path: ../../shared
  image: ^4.2.0
  puppeteer: ^3.17.0
  intl: ^0.20.2
  postgres: ^3.5.6
  drift_postgres: ^1.3.0
  dotenv: ^4.2.0

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.23.1
  lints: ^5.0.0
  test: ^1.25.8


