name: Telegram Bot CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'bot/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'bot/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: bot

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file with TOKEN from secrets
      run: |
        echo "TOKEN=${{ secrets.BOT_TOKEN }}" > .env

    - name: Test bot start
      run: |
        python test\test.py --lifetime 15

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t bot .
