name: Flutter Frontend CI

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.3
          channel: stable
          cache: true

      - name: Create .env file
        working-directory: frontend
        run: |
          touch .env
          cat .env
      
      - name: Code generation in shared folder
        run: |
          dart run build_runner build --delete-conflicting-outputs
        working-directory: shared
      
      - name: Code generation in frontend folder
        working-directory: frontend
        run: |
          dart run build_runner build --delete-conflicting-outputs

      - name: Build web for Web Assembly
        working-directory: frontend
        run: |
          flutter config --enable-web
          flutter build web --wasm --dart-define=MODE=PROD
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create docker-compose.frontend.yml
        run: |
          cat <<EOF > docker-compose.frontend.yml
            version: '3.8'

            services:
              frontend:
                container_name: frontend
                build:
                  context: .
                  dockerfile: ./frontend/Dockerfile
            EOF

      - name: Build Docker image
        run: |
          docker compose -f docker-compose.frontend.yml build
