name: Flutter Frontend CI

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.3
          channel: stable
          cache: true

      - name: Create env file
        run: |
          touch .env
          cat .env
      
      - name: Code generation in shared folder
        run: |
          dart run build_runner build --delete-conflicting-outputs
        working-directory: shared
      
      - name: Code generation in frontend folder
        run: |
          dart run build_runner build --delete-conflicting-outputs

      - name: Build web
        run: |
          flutter config --enable-web
          flutter build web --wasm --dart-define=MODE=PROD
